spring:
  jpa:
    hibernate:
      ddl-auto: validate
    #    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        jdbc:
          batch_size: 20
    open-in-view: false
  datasource:
    url: jdbc:h2:mem:directory
    #    tcp: jdbc:h2:tcp://localhost:9092/mem:directory
    username: sa
    password:

  cache:
    cache-names: companies
    caffeine.spec: maximumSize=5000,expireAfterAccess=600s

  liquibase:
    change-log: "classpath:db/changelog.sql"

logging:
  level:
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG
    org.springframework.cache: TRACE
    org.springframework.web: TRACE
    liquibase: DEBUG

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  forward-headers-strategy: framework

springdoc.swagger-ui.path: /