spring:
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        jdbc:
          batch_size: 20
  datasource:
    url: jdbc:h2:mem:directory
#    tcp: jdbc:h2:tcp://localhost:9092/mem:directory
    username: sa
    password:

logging:
  level:
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG