spring:
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:directory
#    tcp: jdbc:h2:tcp://localhost:9092/mem:directory
    username: sa
    password: